name: digi_test_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  pretty_dio_logger: ^1.3.1

  built_collection: ^5.1.1
  built_value: ^8.9.2
  json_annotation: ^4.9.0

  google_maps_flutter: ^2.9.0

  flutter_smart_dialog: 4.2.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  envied: ^0.5.4+1
  get: ^4.6.6
  get_it: ^8.0.0
  just_audio: ^0.9.41
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  easy_localization: ^3.0.7
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/